<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Education</name>
   <tag></tag>
   <elementGuidId>2d0a14f5-78ee-4baf-ad9d-25f9e2a25d35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='FAU - BA Computer Science (in progress)'])[1]/preceding::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2af1b336-0e63-433b-9033-6dd061d50d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center mb-3 mt-3</value>
      <webElementGuid>b98c0095-783a-4301-90b7-67a059589187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Education</value>
      <webElementGuid>9b341261-a5e1-44c8-94eb-28a863b7a2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;d-grid gap-5&quot;]/div[@class=&quot;text-center mb-3 mt-3&quot;]</value>
      <webElementGuid>38994a49-6060-444b-8c6e-6ccb0f0fa21d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAU - BA Computer Science (in progress)'])[1]/preceding::div[1]</value>
      <webElementGuid>2634d1ad-7b61-4f41-8757-d59cb76b62e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rowan University - AA Computer Science'])[1]/preceding::div[2]</value>
      <webElementGuid>b1b2b4a3-b302-42dd-b5e2-2ddc7b48b5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]</value>
      <webElementGuid>c469a7ec-451b-4f72-8c79-b25db5f3f0ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Education' or . = 'Education')]</value>
      <webElementGuid>59d9d886-ebed-41ed-8055-4b730ecc1f26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
