<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loan Term (years)_term</name>
   <tag></tag>
   <elementGuidId>41fc2939-c8ec-4268-bc36-a0a8a123c05e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#term</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='term']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02f8a0c8-0823-47b7-9f95-7f8e7bce6d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>96038e66-5ca3-48ab-bdb5-213257cf49de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c6d3aaef-c514-41db-b509-168bb7a2a81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>term</value>
      <webElementGuid>4b60142e-5976-4403-b181-8f37cc8a5b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;term&quot;)</value>
      <webElementGuid>381bd5fb-b041-484c-a041-e647756373e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='term']</value>
      <webElementGuid>bcb48494-8563-4023-a117-cc1d44b2eb71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loan-form']/input[3]</value>
      <webElementGuid>0b446485-edd8-48d4-97ed-5af2c28a8fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>143781cc-0ca9-453d-8f5d-960d11c89362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'term']</value>
      <webElementGuid>72a73034-066d-4178-a1f6-8f5d7e4ab93b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
