<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Principal Amount_principal</name>
   <tag></tag>
   <elementGuidId>cd27be72-58d7-489b-a8bb-9dbff600c6e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#principal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='principal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb249c8a-38e8-45d5-9819-d001b7f9a453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4f39b1ab-6ef9-4fea-8ca9-83ffd1ad985c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>28926ecd-8314-4aec-910f-921ffa607db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>principal</value>
      <webElementGuid>7d063c4a-06e0-4340-86bb-a0ccbff19415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;principal&quot;)</value>
      <webElementGuid>56699702-e715-4c38-b894-dc65fbd31a61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='principal']</value>
      <webElementGuid>d5f16f33-cc5d-4ae1-8166-46262bf6dfe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loan-form']/input</value>
      <webElementGuid>736885f3-3df2-4f9f-8b82-8bfe2c952b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6a1c3dfb-011b-4028-a34c-2273d29aa702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'principal']</value>
      <webElementGuid>eedd1f00-2225-449e-82fb-b9489ab2178d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
