<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Annual Interest Rate ()_interest</name>
   <tag></tag>
   <elementGuidId>501e85a7-0865-40cd-baf8-d4d80e253312</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#interest</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='interest']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a74c2cd-57e1-4e46-9b2f-4d8f0b572de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2296f1d1-4706-4724-ade7-6718e9255c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>c4445078-942d-4c50-86ae-ac201b65ff3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>interest</value>
      <webElementGuid>346b95b7-d485-4813-aafb-5408b64e8dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;interest&quot;)</value>
      <webElementGuid>8eee0015-f7d2-4fd6-9d5a-28bd525651fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='interest']</value>
      <webElementGuid>c867a0f9-db4d-4fa7-8c48-cb2a98766c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loan-form']/input[2]</value>
      <webElementGuid>e64a03dd-4834-46fd-8f72-d44aad4b4110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>9297c18a-fd0b-49e6-8f3a-4bf257cc8046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'interest']</value>
      <webElementGuid>dd6d55bf-ee0c-4772-96df-0e7e54ae4a31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
