<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_-0.00</name>
   <tag></tag>
   <elementGuidId>560ce526-1f06-4968-8eaf-bc610d6d24c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tbody:nth-of-type(361) > tr > td:nth-of-type(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='amortization-schedule']/tbody[361]/tr/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5c9df581-8c5f-4de2-bf97-46c2c38998f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$-0.00</value>
      <webElementGuid>a5192467-d7ed-4e3e-95b3-be9b48be95db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amortization-schedule&quot;)/tbody[361]/tr[1]/td[5]</value>
      <webElementGuid>5f48844b-3627-40a0-a67a-cb3b547bf46c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='amortization-schedule']/tbody[361]/tr/td[5]</value>
      <webElementGuid>fbb5a289-bf01-44b7-b75d-9b2808ab6d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$3.77'])[1]/following::td[1]</value>
      <webElementGuid>586fc4ce-7fbc-4a7d-88ea-11be226b1863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$654.83'])[2]/following::td[2]</value>
      <webElementGuid>a41f2e9d-5ff1-4dbe-91f8-5aff2dc8f041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to my home page'])[1]/preceding::td[1]</value>
      <webElementGuid>335546f8-e6a6-4d9b-996b-d1a5e00c0441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View me on GitHub'])[1]/preceding::td[1]</value>
      <webElementGuid>571ce96f-dbc1-4fbf-ad56-cae5245a7c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$-0.00']/parent::*</value>
      <webElementGuid>8452d054-9e9b-4971-8d24-9214f11606ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[361]/tr/td[5]</value>
      <webElementGuid>027bcb3f-b1b7-4562-a62b-320826d4573b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '$-0.00' or . = '$-0.00')]</value>
      <webElementGuid>8f1e059e-cf24-4756-bdbf-4df1bb838b53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
