<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_360</name>
   <tag></tag>
   <elementGuidId>b5356d3d-90af-4f6f-ad92-14995f4b4030</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tbody:nth-of-type(361) > tr > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='amortization-schedule']/tbody[361]/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>4df13c58-428c-4b4b-96c3-61f832df1b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>360</value>
      <webElementGuid>f2b462ef-82fa-41d3-a64d-f2ce213544be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amortization-schedule&quot;)/tbody[361]/tr[1]/td[1]</value>
      <webElementGuid>7e3e408e-c204-4175-9f7b-40e67f86b2a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='amortization-schedule']/tbody[361]/tr/td</value>
      <webElementGuid>3f1b688f-0d5a-4306-8a04-d588ca33d7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$654.83'])[1]/following::td[1]</value>
      <webElementGuid>dba3fb79-91fa-493e-932a-e1ade9686756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$7.51'])[1]/following::td[2]</value>
      <webElementGuid>d6cccec6-3388-40f6-9608-051ea7425bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$658.60'])[360]/preceding::td[1]</value>
      <webElementGuid>4ef82837-fd65-4df2-be74-c919251ef9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$654.83'])[2]/preceding::td[2]</value>
      <webElementGuid>69e892e0-010d-45ac-9ce5-1d3fafe9987c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='360']/parent::*</value>
      <webElementGuid>fd6ba3ee-b62f-488a-bc6d-a19523314d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[361]/tr/td</value>
      <webElementGuid>86326ee6-fcfd-49c3-9353-3283924399b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '360' or . = '360')]</value>
      <webElementGuid>fe035e4f-b238-45d1-ae76-86dc7a707dff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
