<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_3.77</name>
   <tag></tag>
   <elementGuidId>20e0ffe3-be20-4daa-995f-6e88e1337b13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tbody:nth-of-type(361) > tr > td:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='amortization-schedule']/tbody[361]/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1ddc631f-7cb2-44af-ac08-697c91d51622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$3.77</value>
      <webElementGuid>9a2535da-71fb-4dc8-b301-2f9298478a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amortization-schedule&quot;)/tbody[361]/tr[1]/td[4]</value>
      <webElementGuid>f4a65b48-f202-4748-b625-46b842486e76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='amortization-schedule']/tbody[361]/tr/td[4]</value>
      <webElementGuid>7c8f42d5-c968-4bff-bf13-ad15a12511be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$654.83'])[2]/following::td[1]</value>
      <webElementGuid>59670d5b-bd08-450d-8c85-3140556f84a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$658.60'])[360]/following::td[2]</value>
      <webElementGuid>d5246f91-95e2-4bdc-9275-b8a3a21c6d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$-0.00'])[1]/preceding::td[1]</value>
      <webElementGuid>20156b52-edf5-461d-a050-d5377b7a2491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to my home page'])[1]/preceding::td[2]</value>
      <webElementGuid>c953ae29-6d33-42ab-b236-44b614a0e5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$3.77']/parent::*</value>
      <webElementGuid>508fcc51-211b-4756-a474-8876db422f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[361]/tr/td[4]</value>
      <webElementGuid>cebbe1ab-c945-4017-bcdf-f25a35b91b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '$3.77' or . = '$3.77')]</value>
      <webElementGuid>b92a2eba-365a-4210-9135-35a90763fa35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
