<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_658.60</name>
   <tag></tag>
   <elementGuidId>128e431c-aca5-470b-9022-0166cd44cd6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tbody:nth-of-type(361) > tr > td:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='amortization-schedule']/tbody[361]/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0c33a363-48d7-490e-bb23-498b1e44aa75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$658.60</value>
      <webElementGuid>293ac131-ba2e-4484-8c7f-e0835d6f44d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amortization-schedule&quot;)/tbody[361]/tr[1]/td[2]</value>
      <webElementGuid>aea3e034-6649-4403-956e-b94e9bbd388a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='amortization-schedule']/tbody[361]/tr/td[2]</value>
      <webElementGuid>0596e7fe-3a60-440b-9aad-9573bff4b6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$654.83'])[1]/following::td[2]</value>
      <webElementGuid>84bea1d2-37f6-45f9-8ca0-b87b314121bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$7.51'])[1]/following::td[3]</value>
      <webElementGuid>5fe8f46a-f405-419d-aec7-f6b33eb7bbfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$654.83'])[2]/preceding::td[1]</value>
      <webElementGuid>5111e087-c152-4d44-910b-b235eb9b6d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$3.77'])[1]/preceding::td[2]</value>
      <webElementGuid>13cfc1b5-11ab-4ea7-b2ba-e27e84f7244f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[361]/tr/td[2]</value>
      <webElementGuid>dfe94bc7-8cbf-4280-a7b8-19517afa8af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '$658.60' or . = '$658.60')]</value>
      <webElementGuid>a7fced9b-59b8-4c27-bf7a-6d597461c636</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
