<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_654.83</name>
   <tag></tag>
   <elementGuidId>8c2301fe-744b-402d-b78c-032c8ef37596</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tbody:nth-of-type(361) > tr > td:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='amortization-schedule']/tbody[361]/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f2746a18-93f1-456a-9542-6cb6c6061654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$654.83</value>
      <webElementGuid>041c52f3-6faf-4311-9548-c2952d7e1f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amortization-schedule&quot;)/tbody[361]/tr[1]/td[3]</value>
      <webElementGuid>70871d9d-7173-488f-8998-466dac57fe19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='amortization-schedule']/tbody[361]/tr/td[3]</value>
      <webElementGuid>c2e4b59d-7be9-4ca0-84ab-12a0bdec2dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$658.60'])[360]/following::td[1]</value>
      <webElementGuid>3cd2fdb7-bb83-45f1-9312-f304e24da00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$654.83'])[1]/following::td[3]</value>
      <webElementGuid>8b15e3c0-097a-48c2-9e15-136bd50c30ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$3.77'])[1]/preceding::td[1]</value>
      <webElementGuid>504fca66-f420-489b-ae99-d0dd6c9f7be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$-0.00'])[1]/preceding::td[2]</value>
      <webElementGuid>fcdbf071-59c5-4460-a329-e796a4eb97ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[361]/tr/td[3]</value>
      <webElementGuid>695115c2-e92a-4459-9c67-fa5bcc6127c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '$654.83' or . = '$654.83')]</value>
      <webElementGuid>38097112-9e9f-4ce9-a6b0-0502c8890481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
